In [ ]:
"""
案例:
    演示参数初始化的 7 种方式.

参数初始化的目的:
    1. 防止梯度消失 或者 梯度爆炸.
    2. 提高收敛速度.
    3. 打破对称性.

参数初始化的方式:
    无法打破对称性的:
        全0, 全1, 固定值
    可以打破对称性的:
        随机初始化, 正态分布初始化, kaiming初始化, xavier初始化

总结:
    1. 记忆 kaiming初始化, xavier初始化, 全0初始化.
    2. 关于初始化的选择上:
        激活函数ReLU及其系列: 优先用 kaiming
        激活函数非ReLU: 优先用 xavier
        如果是浅层网络: 可以考虑使用 随机初始化
"""

In [1]:
# 导包
import torch.nn as nn

In [5]:
# 1.均匀分布随机初始化
def dm01():
    # 1.创建1个线性层, 输入维度5, 输出维度3
    linear=nn.Linear(5,3)
    # 2.对权重(w)进行随机初始化，从0-1均匀分布产生参数
    nn.init.uniform_(linear.weight)
    # 3.对偏置(b)进行随机初始化，从0-1均匀分布产生参数
    nn.init.uniform_(linear.bias)
    # 4.打印生成结果
    print(linear.weight.data)
    print(linear.bias.data)
dm01()

tensor([[0.8388, 0.8070, 0.9553, 0.8959, 0.1800],
        [0.3625, 0.4856, 0.6801, 0.0245, 0.2986],
        [0.7066, 0.7134, 0.4679, 0.2261, 0.3601]])
tensor([0.2448, 0.1420, 0.2455])


In [6]:
# 2.固定初始化
def dm02():
    # 1. 创建1个线性层, 输入维度5, 输出维度3
    linear = nn.Linear(5, 3)
    # 2. 对权重(w)进行初始化, 设置固定值为: 3
    nn.init.constant_(linear.weight, 3)
    # 3. 对偏置(b)进行初始化, 设置固定值为: 3
    nn.init.constant_(linear.bias, 3)
    # 4. 打印生成结果.
    print(linear.weight.data)
    print(linear.bias.data)
dm02()

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([3., 3., 3.])


In [9]:
# 4. 全1初始化
def dm04():
    # 1. 创建1个线性层, 输入维度5, 输出维度3
    linear = nn.Linear(5, 3)
    # 2. 对权重(w)进行初始化, 全1初始化
    nn.init.ones_(linear.weight)
    # 3. 打印生成结果.
    print(linear.weight.data)
dm04()

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [11]:
# 5. 正态分布随机初始化
def dm05():
    # 1. 创建1个线性层, 输入维度5, 输出维度3
    linear = nn.Linear(5, 3)
    # 2. 对权重(w)进行初始化, 正态分布初始化(均值为0, 标准差为1)
    nn.init.normal_(linear.weight)
    # 3. 打印生成结果.
    print(linear.weight.data)
dm05()

tensor([[ 1.1799, -0.6151,  1.0738,  0.7949, -0.0567],
        [ 0.5658, -0.7853, -0.5412, -1.3057, -0.7108],
        [-1.0204, -1.0066, -0.2085,  0.6629,  1.0881]])


In [20]:
# 6. kaiming 初始化
def dm06():
    # 1. 创建1个线性层, 输入维度5, 输出维度3
    linear = nn.Linear(5, 3)
    # 2. 对权重(w)进行初始化, 正态分布初始化(均值为0, 标准差为1)
    # kaiming 正态分布初始化
    # nn.init.kaiming_normal_(linear.weight)

    # kaiming 均匀分布初始化
    nn.init.kaiming_uniform_(linear.weight)
    # 3. 打印生成结果.
    print(linear.weight.data)

dm06()

tensor([[ 0.2203,  0.8008, -0.0337, -0.0093, -0.4240],
        [ 0.0273,  0.7274, -0.2781, -0.1959, -0.1006],
        [-0.5469, -0.7216, -0.6376, -0.7978, -0.6100]])


In [21]:
# 7. xavier 初始化
def dm07():
    # 1. 创建1个线性层, 输入维度5, 输出维度3
    linear = nn.Linear(5, 3)
    # 2. 对权重(w)进行初始化, 正态分布初始化(均值为0, 标准差为1)
    # xavier 正态分布初始化
    # nn.init.xavier_normal_(linear.weight)

    # xavier 均匀分布初始化
    nn.init.xavier_uniform_(linear.weight)

    # 3. 打印生成结果.
    print(linear.weight.data)
dm07()

tensor([[ 0.0103, -0.3985, -0.6972,  0.1356,  0.5462],
        [ 0.3831, -0.2265, -0.7080, -0.0528, -0.4744],
        [ 0.2223, -0.1599, -0.5160,  0.2772, -0.7660]])
